//
// Created by myrddin on 06/12/16.
//

#ifndef TOWERDEFENSE_USERINTERACTIONINTERFACE_H
#define TOWERDEFENSE_USERINTERACTIONINTERFACE_H


class UserInteractionInterface {

};


#endif //TOWERDEFENSE_USERINTERACTIONINTERFACE_H
